### ISSUE TITLE
Replace tip-submission text-line with a paragraph box?

### ISSUE THREAD

**Issue by milo-trujillo** [DaylightingSociety/SpeakFree#11]
Would it be better if we replaced the single-line text entry for a new tip with a full paragraph box? This would make it easier to enter longer tips and might look better, but maybe we want to leave the current text entry system to incentivize writing shorter tips.

**Comment by tfdahlin** [comment]
Implemented; android doesn't seem to have an option to default to a paragraph-sized box by default (that I can easily find), but the box now wraps the text into paragraph form.
