### ISSUE TITLE
Replace the 'plus' and 'reload' button images

### ISSUE THREAD

**Issue by milo-trujillo** [DaylightingSociety/SpeakFree#12]
All of the UI buttons are 64x64 pixel PNGs, except the 'plus' and 'reload' buttons, which are 32x32 pixels. As a result, these two buttons look grainy on phones and tablets when the other buttons do not.

**Comment by tfdahlin** [comment]
It doesn't appear that I have 64x64 assets for these particular icons; I grabbed the icons for the iOS version's folder, and have been using the "@2x" icons. Most of these were 64x64. However, it looks like these two particular icons are 32x32 (and the standard-sized icons are 16x16).

**Comment by milo-trujillo** [comment]
Ah, I'll bet iOS doesn't have 64x64 because we implemented #13 over there. If OpenIconic doesn't have that size then I probably took the SVG versions and exported them at 64x64.

**Comment by milo-trujillo** [comment]
Generated some 64x64 PNGs and plopped them in.
