### ISSUE TITLE
Use smaller buttons on sides of MainActivity button bar?

### ISSUE THREAD

**Issue by milo-trujillo** [DaylightingSociety/SpeakFree#13]
I think the UI looks more natural with slightly smaller buttons on the sides of the action bar - it draws focus to the play/pause button, which is the main action of the app. Here's an example of what this looks like in the iOS app:

![iOS Action Bar](https://i.imgur.com/wjLa3Lz.png)

Should we make this change on Android as well?

**Comment by tfdahlin** [comment]
This definitely looks better; I have very slightly increased the size of the play button, and decreased the size of the other buttons by 1/3.
