### ISSUE TITLE
Add tip download confirmation

### ISSUE THREAD

**Issue by milo-trujillo** [DaylightingSociety/SpeakFree#7]
Since the "reload" button doesn't have immediately obvious meaning, and many of our users are very privacy conscious and won't want network calls made without their permission, let's add a confirmation popup when they press the reload button.

For reference, [here's the pop-up on iOS](https://github.com/DaylightingSociety/SpeakFree/blob/master/iOS/SpeakFree/SpeakFree/ViewController.m#L104-L125), which looks like:

![SpeakFree on iOS](https://i.imgur.com/u4D9d5A.jpg)

**Comment by tfdahlin** [comment]
Added!
