### ISSUE TITLE
Fix arrow direction on info panel

### ISSUE THREAD

**Issue by milo-trujillo** [DaylightingSociety/SpeakFree#8]
To open the info panel you press a button on the right of the main button bar. To close the info panel you would expect a return arrow aiming left, or maybe an exit button in the center, but not another arrow pointing right.

Can we swap out the exit arrow for the info panel with one pointing left on the left side of the bar, or an 'x' in the middle? If we go for the 'x' let's update the help panel, too.

**Comment by tfdahlin** [comment]
Opted for putting exit arrow on the left hand side instead (also fixed a related issue with smaller screen sizes)
