### ISSUE TITLE
Add feedback when a tip is submitted

### ISSUE THREAD

**Issue by milo-trujillo** [DaylightingSociety/SpeakFree#9]
Right now when the user submits a new tip the tip textbox disappears and they return to the main screen. This leaves it ambiguous as to whether the tip went anywhere.

Let's add a pop-up thanking the user for their submission if the tip went through, or announcing an error if it couldn't be submitted.

**Comment by tfdahlin** [comment]
Feedback has been added! And I fixed a bug with other similar notifications that I wasn't aware of until just now c:
